closes ISS 337.  Export Chart button removed.  Occupation/Salary togg…
codeforboston/jobhopper pull request #356
Opened 2021-04-06 19:59 UTC by jkoren

…le only on Tree Map visualization.

2021-04-06 23:33 UTC, alexjball requested changes
Please fix the warnings shown under "files changed". You can check that there are no warnings locally by running `npm run lint`. Removing exportPDF might produce new warnings.

2021-04-06 23:34 UTC, alexjball requested changes

2021-04-06 23:34 UTC, alexjball commented on frontend/src/ui/Results/Results.tsx
> +  const exportChart = '';
Let's remove the commented out lines and the `exportChart` constant. We can always pull up this this code again using git.

2021-04-07 15:42 UTC, jkoren commented
Made requested changes. I removed the commented out lines and the exportChart constant.   
npm run link gave errors on exportPDF, Canvg, and jsPDF which are no longer used, so I removed that code as well.

Errors from lint:
```
warning  'exportPDF' is assigned a value but never used  @typescript-eslint/no-unused-vars
warning  'Canvg' is defined but never used    @typescript-eslint/no-unused-vars
warning  'jsPDF' is defined but never used    @typescript-eslint/no-unused-vars
```

2021-04-07 21:20 UTC, alexjball approved these changes

2021-04-07 21:20 UTC, merged